name: react-rust-postgres
services:
  frontend:
    build:
      context: ./project_frontend/
    ports:
      - 5175:5175

  backend:
    build:
      context: ./project_back/
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: "project_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1530"
    ports:
      - 5432:5432